### ISSUE TITLE
Add explanation of what "if reqCount >= 10 // Change this to some # you're interested in" means!

### ISSUE THREAD

**Issue by epugh** [mikepugh/angular-http-throttler#5]
Hi,

I babysit a open source tool that sends LOTS of requests to back-end APIs, and sometimes it overwhelms the API.  I'd like to throttle, and I played around with some tools for angular1, no luck, but your installed just fine.

Now..  Can you explain a bit more about how I can conditionally change the reqCount?

My PR is https://github.com/o19s/quepid/pull/1070

I'd like to turn on and off the throttling programmatically, as for some back-ends full rate is fine, and others are more finicky.

**Comment by mikepugh** [comment]
The way this service is currently setup doesn't really lend itself to dynamic max request counts based upon target endpoints. I'd recommend you spin off your own version that can be setup with a hash table of base endpoints to max req count mappings. Something like 

```
[
{"baseUri": "api.weather.com", "maxReqCount": 10},
{"baseUri": "api.xyz.com", "maxReqCount": 100}, 
{"baseUri": "api.abc.com", "maxReqCount": 0}
]
```

Perhaps the value of 0 for maxReqCount could be your signal to never throttle.. just an idea.
